image: node:10.16.3-jessie

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install -g @angular/cli
  - npm install
  - ng build --base-href=/ --env=prod
  artifacts:
    paths:
    - dist
  only:
    - master